/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CreateStrategyModal: typeof import('./src/components/strategy/CreateStrategyModal.vue')['default']
    EditStrategyModal: typeof import('./src/components/strategy/EditStrategyModal.vue')['default']
    Header: typeof import('./src/components/common/Header.vue')['default']
    NotificationContainer: typeof import('./src/components/common/NotificationContainer.vue')['default']
    OptimizationModal: typeof import('./src/components/OptimizationModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StrategyDetailModal: typeof import('./src/components/strategy/StrategyDetailModal.vue')['default']
  }
}
